internalName: kca_keyboard

locales:
  en:
    name: &bundleName "Khanty Keyboards"
    description: "Mobile OS keyboards for the Khanty language from the Divvun group at UiT."
  nb:
    name: "Khanty tastatur"
    description: "Mobiltastatur for Khanty fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [kca]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.kca
    icon: kca-icon.pdf
    keyStore: /Users/brendan/git/softkbdgen/test.keystore
    keyAlias: kca_keyboard

  ios: &AppleID
    codeSignId: "iOS Development"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.kca
    bundleName: *bundleName
    icon:
        90: kca-icon-small.png
        150: kca-icon.png
  osx: *AppleID
