locales:
  en:
    name: Khanty Keyboards
    description: Mobile OS keyboards for the Khanty language from the Divvun group at UiT.
  nb:
    name: Khanty tastatur
    description: Mobiltastatur for Khanty fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
